services:
  - type: web
    name: telegram-card-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python render_main.py"
    plan: free
    region: frankfurt
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PORT
        fromGroup: web
      - key: DISPLAY_CHANNEL
        value: "-1002299981135"
      - key: PREDICTION_INTERVAL
        value: "1"
    healthCheckPath: "/health"
