services:
  - type: web
    name: telegram-bot-baccarat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python render_main.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
